### ISSUE TITLE
Test failure CrossMenuAssignmentTest::testFormSubmission

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov_menu_link_group#40]
```
Drupal\Tests\localgov_menu_link_group\Kernel\CrossMenuAssignmentTest::testFormSubmission
Failed asserting that an array is empty.

/var/www/html/vendor/phpunit/phpunit/src/Framework/Constraint/Constraint.php:122
/var/www/html/vendor/phpunit/phpunit/src/Framework/Constraint/Constraint.php:56
/var/www/html/web/modules/contrib/localgov_menu_link_group/tests/src/Kernel/CrossMenuAssignmentTest.php:78
/var/www/html/vendor/phpunit/phpunit/src/Framework/TestResult.php:729
```

**Comment by millnut** [comment]
~Hi @stephen-cox I think this might just need a new release, as the action results from the `1.x` branch all succeed and the last release was in May.~

~So I wonder whether something between then and now has fixed the failed test shown in the project and this just needs a new released published~

Hmm maybe not as I've just compared the last release to the `1.x` branch and the only change is the workflow.

Seems like this worked in Drupal 10.2.7 and then stopped working with Drupal 10.3
