### ISSUE TITLE
Tag 1.0.0

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov_menu_link_group#6]
As per localgovdrupal/localgov#194 localgovdrupal/localgov#200

PR/Issue #3 #5 Check not blocking.

**Comment by ekes** [comment]
@andybroomfield Should we try and get #5 in before tagging? 
It does expose items to users without permission, but on the other hand it's in admin. Alternatively is there something easy to nudge it along?

**Comment by andybroomfield** [comment]
@ekes I'd like to get it in if possible, as it does confuse things for users who only have limited permissions.
The PR I raised does work from my manual testing, however I am struggling to write the test for it. @Adnan-cds was going to take a look, or if anyone wants to take over. Basically create some menu groups that include only things a user won't have permission for and check the group is excluded.

**Comment by Adnan-cds** [comment]
Okay, I will have a look at #5 later today.  Sorry for holding you back.

**Comment by Adnan-cds** [comment]
Sorry, got late again.  I am looking into #5 now.

**Comment by ekes** [comment]
So #200 can be round off #5 can go into a 1.0.1 or 1.0.2

**Comment by ekes** [comment]
https://github.com/localgovdrupal/localgov_menu_link_group/releases/tag/1.0.0
